### ISSUE TITLE
Error: unrecognized cop or department RSpecRails/HttpStatus found in config/default.yml Did you mean `RSpecRails/HaveHttpStatus`? 

### ISSUE THREAD

**Issue by rubyonrails3** [rubocop/rubocop-rspec_rails#9]
I am getting this error, today suddenly my CI stopped working, as my Gemfile.lock is not part of the gem and it installs the latest available gems. 

Error: unrecognized cop or department RSpecRails/HttpStatus found in /Users/ismail/.rvm/gems/ruby-3.3.0/gems/rubocop-rspec_rails-2.28.1/config/default.yml
Did you mean `RSpecRails/HaveHttpStatus`?

Any idea about it?

**Comment by mjankowski** [comment]
It looks like you closed/moved the PRs before I could try. As of right now, when I attempt to use https://github.com/rubocop/rubocop-rspec_rails/pull/10 by doing (this is using revision 38ee3c7):

```
gem "rubocop-rspec_rails", github: "rubocop/rubocop-rspec_rails", branch: "fix-error"
```

I still get the same error we saw on CI:

> Error: Ambiguous cop name `RSpec/Rails/HttpStatus` used in /Users/mjankowski/repos/mastodon/.rubocop.yml needs department qualifier. Did you mean Rails/HttpStatus or RSpecRails/HttpStatus?

Perhaps notable here ... are the errors starting with "Error: unrecognized cop or department" (this PR) and "Error: Ambiguous cop name" (my local and CI failure) actually the same thing? Or are there related separate issues?

**Comment by mjankowski** [comment]
Update - just saw new commit as I posted comment. I see the same error with ab5f37ef9f9b6aa6f3a675f62f50c431b39a50a5 as well

**Comment by ntkme** [comment]
@mjankowski I think that is a slightly different issue that the alias defined here is somehow not working as intended: https://github.com/rubocop/rubocop-rspec/blob/e6b53cbfa6b24222c19b7c6c78dd7c11681e1ba0/lib/rubocop/cop/rspec/rails/http_status.rb#L57

**Comment by mjankowski** [comment]
Shall I open a separate issue to focus narrowly on the ambiguous/alias case, and let this issue focus on the rack/unrecognized issue?

**Comment by ydah** [comment]
@mjankowski Does adding rack to the Gemfile solve this problem?

**Comment by mjankowski** [comment]
No - `rack` is already in the project Gemfile.

**Comment by ydah** [comment]
@mjankowski I have revived the following PR and branch. How about using the following?
https://github.com/rubocop/rubocop-rspec/pull/1849

**Comment by ntkme** [comment]
> Error: Ambiguous cop name RSpec/Rails/HttpStatus used in /Users/mjankowski/repos/mastodon/.rubocop.yml needs department qualifier. Did you mean Rails/HttpStatus or RSpecRails/HttpStatus?

@ydah I think this message has nothing to do with rack being missing, as @mjankowski says he had rack installed directly. The message indicates the we have cop `Rails/HttpStatus` (somehow missin a `RSpec/` prefix) and `RSpecRails/HttpStatus` available, but not `RSpec/Rails/HttpStatus`...

**Comment by mjankowski** [comment]
More debugging if this is useful....

The `RSpec/Rails/HttpStatus` cop is the ONLY `RSpec/Rails/*` cop we have explicitly used in the configuration.

If I add other cops in the config, I get what I assumed is the expected deprecation warning output, like:

> .rubocop.yml: RSpec/Rails/AvoidSetupHook has the wrong namespace - replace it with RSpecRails/AvoidSetupHook

I only get the ambiguous cop name error for `RSpec/Rails/HttpStatus` specifically.

**Comment by boris-petrov** [comment]
I'm a bit confused by this thread. I don't have anything Rails-related in my project. Why is `rubocop-rspec` installing/using `rubocop-rspec_rails`?

**Comment by pirj** [comment]
Wondering how this worked when the cop was called RSpec/Rails/HttpStatus? 🤔 Was it conditionally loaded, too?
We didn’t have aliasing. Is it the aliasing that fails, while a regular configloader tolerates having a config for a missing cop?

**Comment by pirj** [comment]
> I  don't have anything Rails-related in my project. Why is rubocop-rspec installing/using rubocop-rspec_rails?

We had rspec-rails related cops in rubocop-rspec in the previous minor version. Now, they are extracted to a separate repo. For semantic versioning purposes, we can’t just drop them in a minor version from rubocop-rspec.

**Comment by boris-petrov** [comment]
> For semantic versioning purposes, we can’t just drop them in a minor version from rubocop-rspec.

I'm not sure that *removing* things in minor versions is a problem under semantic versioning. I think minor versions are only supposed to not break user code (like introduce backward-incompatible changes - unless they are bug-fixes). Removing things won't break user code. It just won't handle as many cases - but that's fine - users can just install the new package and get the same behavior.

I'm just mentioning it from a philosophical point of view, I'm totally fine with you only removing the cops in the next major.

**Comment by pirj** [comment]
@boris-petrov removing cops that are explicitly referenced in our uaer’s project tubocop config files could cause breakages, doesn’t it? The fact that it’s easily fixed by adding rubocop-rapec_rails to the Gemfile is not an excuse for us. I don’t want to go too deep on why, but for us, it’s unacceptable, and we apply our best efforts at making minor version updates smooth for our users.
Indeed, sometimes, like this time, incidents happen, and we learn how to improve this in the future.

**Comment by boris-petrov** [comment]
@pirj you're absolutely right, I didn't think of the case where people had references to these cops. So that would indeed be a breaking change.

Thanks for the hard work on these RuboCop plugins! The incidents are not a problem at all so no worries about that.

**Comment by ydah** [comment]
FYI, A fixed version has been released:
https://github.com/rubocop/rubocop-rspec_rails/releases/tag/v2.28.2

**Comment by mjankowski** [comment]
Should the 2.28.2 release fix both the "Error: unrecognized cop or department" and also the "Error: Ambiguous cop name" error ... or jus the first one ("unrecognized", rack issue?)

I still see the ambiguous cop name error with `rubocop-rspec` version 2.28.0 and `rubocop-rspec_rails` version 2.28.2.

**Comment by ydah** [comment]
Both should be resolved.
I made the following comment, but is it v 2.28.1? Does it happen even if I update to v 2.28.2?
https://github.com/mastodon/mastodon/pull/29804#discussion_r1546237097

**Comment by mjankowski** [comment]
Ok, let me try to recreate a minimal reproduction case and report back. I'll open a new issue for the ambiguous error specifically if I'm able to.

This PR - https://github.com/mastodon/mastodon/pull/29806/files - which does update to 2.28.2 - still shows the ambiguous error unless I rename the cop. Maybe we have something else going on in our load order or config or something. I'll poke around.
